[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version" # prevent Netlify npm install

[build]
  publish = "docs_dist"
  command = "pnpm docs:build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
